//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.XDS.Test.XDSRegistry
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ihe:iti:xds-b:2007", ConfigurationName="Microsoft.XDS.Test.XDSRegistry.XDSRegistry")]
    public interface XDSRegistry
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2007:RegistryStoredQuery", ReplyAction="urn:ihe:iti:2007:RegistryStoredQueryResponse")]
        System.ServiceModel.Channels.Message RegistryStoredQuery(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2007:RegisterDocumentSet-b", ReplyAction="urn:ihe:iti:2007:RegisterDocumentSet-bResponse")]
        System.ServiceModel.Channels.Message RegisterDocumentSet(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:hl7-org:v3:PRPA_IN201301UV", ReplyAction="urn:hl7-org:v3:MCCI_IN000002UV")]
        System.ServiceModel.Channels.Message PatientRegistryRecordAdded(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:hl7-org:v3:PRPA_IN201302UV", ReplyAction="urn:hl7-org:v3:MCCI_IN000002UV")]
        System.ServiceModel.Channels.Message PatientRegistryRecordRevised(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:hl7-org:v3:PRPA_IN201304UV", ReplyAction="urn:hl7-org:v3:MCCI_IN000002UV")]
        System.ServiceModel.Channels.Message PatientRegistryDuplicatesResolved(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface XDSRegistryChannel : Microsoft.XDS.Test.XDSRegistry.XDSRegistry, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class XDSRegistryClient : System.ServiceModel.ClientBase<Microsoft.XDS.Test.XDSRegistry.XDSRegistry>, Microsoft.XDS.Test.XDSRegistry.XDSRegistry
    {
        
        public XDSRegistryClient()
        {
        }
        
        public XDSRegistryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public XDSRegistryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public XDSRegistryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public XDSRegistryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.ServiceModel.Channels.Message RegistryStoredQuery(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.RegistryStoredQuery(request);
        }
        
        public System.ServiceModel.Channels.Message RegisterDocumentSet(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.RegisterDocumentSet(request);
        }
        
        public System.ServiceModel.Channels.Message PatientRegistryRecordAdded(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.PatientRegistryRecordAdded(request);
        }
        
        public System.ServiceModel.Channels.Message PatientRegistryRecordRevised(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.PatientRegistryRecordRevised(request);
        }
        
        public System.ServiceModel.Channels.Message PatientRegistryDuplicatesResolved(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.PatientRegistryDuplicatesResolved(request);
        }
    }
}
