
USE XDSRegistryDB
DELETE FROM SUBMISSIONSETAUTHOR
DELETE DOCUMENTENTRYAUTHOR
DELETE FROM AUTHOR
DELETE FROM SUBMISSIONSETDOCUMENTFOLDER
DELETE FROM SUBMISSIONSET
DELETE FROM FOLDERCODELIST
DELETE FROM FOLDER
DELETE DOCUMENTENTRYEVENTCODELIST
DELETE FROM DOCUMENTENTRY
DELETE FROM REGISTRYLOG


USE XDSRepositoryDB
DELETE FROM DOCUMENTENTRYLOG
DELETE FROM DOCUMENTREPOSITORYMETADATA
DELETE FROM DOCUMENTCONTENT
DELETE FROM DOCUMENTREPOSITORYLOG

